[dependencies]
  charset4cj = {branch = "v0.0.1.B003", git = "https://gitcode.com/Cangjie-TPC/charset4cj.git"}

[package]
  cjc-version = "0.56.4"
  compile-option = "-O2 -Woff all"
  description = "nothing here"
  link-option = ""
  name = "zip4cj"
  output-type = "dynamic"
  src-dir = "src"
  target-dir = ""
  version = "0.0.2"
  package-configuration = {}
  scripts = {}


