[dependencies]
  charset = {branch = "develop", git = "https://gitee.com/HW-PLLab/charset.git", version = "0.0.2"}
  crypto4cj = {branch = "add_pbkdf2", git = "https://gitee.com/HW-PLLab/crypto4cj.git", version = "0.0.7"}

[package]
  cjc-version = "0.51.4"
  compile-option = "-Woff all"
  description = "nothing here"
  link-option = ""
  name = "zip4cj"
  output-type = "dynamic"
  src-dir = "src"
  target-dir = ""
  version = "0.0.2"
  package-configuration = {}
  scripts = {}


[target.x86_64-unknown-linux-gnu]
  compile-option = "-O2"
[target.aarch64-unknown-linux-gnu]
  compile-option = "-O2"